---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux-cachyos"
img: "/boot/initramfs-linux-cachyos.img"
fallback: "/boot/initramfs-linux-cachyos-fallback.img"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootloaderId: "FarmNerdOS"
installEFIFallback: true
