---
defaultGroups:
  - users
  - wheel
  - video
  - input
  - storage
  - network
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
allowWeakPasswords: true
allowWeakPasswordsDefault: false
userShell: /bin/bash
